CLASS PADRE DEFINITION.
    PUBLIC SECTION.
    DATA: W_PUBLIC(30) VALUE 'ESTO ES UN DATO PUBLICO',
          V_PUBLIC(30) VALUE 'PARA SAP'.
    METHODS: PADREMET, CORRER.
ENDCLASS.

CLASS HIJO DEFINITION INHERITING FROM PADRE.
    PUBLIC SECTION.
    METHODS: HIJOMET.
ENDCLASS.

CLASS PADRE IMPLEMENTATION.
    METHOD PADREMET.
        WRITE /: W_PUBLIC.
    ENDMETHOD.
     METHOD CORRER.
        WRITE /: V_PUBLIC.
    ENDMETHOD.
ENDCLASS.

CLASS HIJO IMPLEMENTATION.
    METHOD HIJOMET.
        SKIP.
        WRITE /: 'METODO EN LA CLASE HIJO', W_PUBLIC, V_PUBLIC.
    ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
    DATA:
        PADRE TYPE REF TO PADRE,
        HIJO TYPE REF TO HIJO.

    CREATE OBJECT:  PADRE, HIJO.
    CALL  METHOD:
        PADRE->PADREMET,
        PADRE->CORRER,
        HIJO->HIJOMET.
                